.PHONY: clean All

All:
	@echo "----------Building project:[ arducar - Debug ]----------"
	@"$(MAKE)" -f  "arducar.mk"
clean:
	@echo "----------Cleaning project:[ arducar - Debug ]----------"
	@"$(MAKE)" -f  "arducar.mk" clean
